version: "3.9"
include:
  - .metrics/docker-compose.yml
services:
  otel-demo:
    image: otel-demo
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=otel-demo
    depends_on:
      - otel-collector
