version: "3.9"
services:

  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  loki:
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.1.1
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/loki/promtail-config.yaml
    command: -config.file=/etc/promtail/config.yml

  tempo:
    image: grafana/tempo:2.6.0
    ports:
      - "3200" # tempo
      - "44317:4317" # otlp grpc
      - "44318:4318" # otlp http
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./tempo.yaml:/etc/tempo.yaml"

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
      - prometheus
