{
 "title": "Open Telemetry Demo",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total commands",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "otel_demo_messaging_commands_dispatched_total",
       "legendFormat": "{{command_name}}"
      }
     ]
    },
    {
     "title": "Command rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(otel_demo_messaging_commands_dispatched_total[$__rate_interval])",
       "legendFormat": "{{command_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "otel_demo_messaging_events_dispatched_total",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "Command rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(otel_demo_messaging_events_dispatched_total[$__rate_interval])",
       "legendFormat": "{{event_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "otel_demo_traffic_queue_depth", "legendFormat": "{{traffic_light}}" }
   ]
  },
  {
   "title": "Junction light phases",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "filters": [
      { "id": "c4aa47f6", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "otel-demo" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "JunctionLightPhase" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}